### ISSUE TITLE
Missing constants

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GMEXT-EpicOnlineServices#10]
The extension is missing the following constants:

`EOS_EAuthScopeFlags::EOS_AS_Country`

**Comment by YYBartT** [comment]
A couple more constants that appear to be missing: 
* (members of [EOS_EResult](https://dev.epicgames.com/docs/en-US/api-ref/enums/eos-e-result)):
  * `EOS_EResult::EOS_NetworkDisconnected`
  * `EOS_EResult::EOS_ApplicationSuspended`
  * `EOS_EResult::EOS_Auth_AccountPortalLoadError`
  * `EOS_EResult::EOS_Auth_CorrectiveActionRequired`
  * `EOS_EResult::EOS_Lobby_VoiceNotEnabled`
  * Everything under `EOS_EResult::EOS_Permission_*`
  * Everything under `EOS_EResult::EOS_DesktopCrossplay_*`
* [EOS_ELogCategory](https://dev.epicgames.com/docs/en-US/api-ref/enums/eos-e-log-category):
  * `EOS_LC_IntegratedPlatform`

The following constants are listed in the extension and in the documentation, though have no corresponding constant under [EOS_ELogCategory](https://dev.epicgames.com/docs/en-US/api-ref/enums/eos-e-log-category): 
* `EpicGames_LC_IdentityProvider`
* `EpicGames_LC_Inventory`
* `EpicGames_LC_ReceiptValidator`

**Comment by patchuby** [comment]
This has been solved : the issue was configuration changes that were not properly registered by the IDE, so I had to manually edit project files to get it working. As I understand those kind of issues have been solved in 2024.4 (and I'm in 2024.2) so I think we can close this one.
