### ISSUE TITLE
LoadLibraryW("EpicOnlineServices_x64.dll") failed with error code 87

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GMEXT-EpicOnlineServices#15]
Hello, I am getting the error `LoadLibraryW("EpicOnlineServices_x64.dll") failed with error code 87 ("The parameter is incorrect.")` when trying the latest `main` branch with Epic SDK `EOS-SDK-32303053-v1.16.3` and the tagged commit `1.4.2` with the SDK `EOS-SDK-23143668-v1.15.4`.

I am also seeing a GMC thread of someone getting the error `LoadLibraryW("EpicOnlineServices_x64.dll") failed with error code 87 ("?")`: https://forum.gamemaker.io/index.php?threads/when-do-you-call-eos_initialize.115384/

Is it possible that the compiled the `EpicOnlineServices_x64.dll` is built incorrectly?

**Comment by DiasFranciscoA** [comment]
This is actually not a "bug" and the extension is fully working I'll update the extension so it doesn't show the message is a remaining from the the old initialization system.

**Comment by shichen85** [comment]
Hello, I am still getting this error code 87 with the ` ("The parameter is incorrect.")` message using `v2.0.0` and  `EOS SDK version 1.16.3` for windows YYC. Is there any tips on how to interpret that error message? I am trying to figure out if it was my setup or that the DLL itself is problematic.
