### ISSUE TITLE
[Documentation] Setting up requires configuring the `Product Name` extension option

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GMEXT-EpicOnlineServices#16]
Hello, on the [Setup guide](https://github.com/YoYoGames/GMEXT-EpicOnlineServices/wiki/setup) in the wiki, it mentioned that `The Product ID, Sandbox ID and Deployment ID must be set`. However. if `Product Name` is not set, `EOS_Initialize()` will return the [EOS_InvalidParameters ](https://dev.epicgames.com/docs/en-US/api-ref/enums/eos-e-result) error.

**Comment by DiasFranciscoA** [comment]
Hello @shichen85, thank you for letting us know. This should be new fixed in the wiki now and main branch, for the package there won't be a release until sometime next week. I'll mark this as solved.
